print("**In ThE NaMe Of GoD**")
print("GoD KLR * Shad , Rubika")
print("DaLtOn ErRoR,ShaHzAdeH TiKaFiL")
print("The BeSt KLR HoSeIn DaNiEL RySoN")
print("Bemanad Yadegar Shayad Fardayi Nabashad")
print("1403 - 2024")
print("***Taqdim : Bax Carter , Makan Tomar , Bax Mordegan , Bax Tomar , Beni Carter , Daniel Rayson , Bax Begacifer , Mmd Jena , Allah Tikafil , DaLtoN ErRor , Mr Mmd Reporter***")
print("~~~Record To Filtering : Fil account 'rubika' 7 Ellie 3 Min~~~")
print("•I'M ' 17 Age•")
print("      *****     ")
print(".<script.Yadegari>.")
print("∅I live in the city of Tabriz∅")